# Generated by Django 4.1.5 on 2023-01-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Perfession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Singer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                ("avatar", models.ImageField(null=True, upload_to="")),
                (
                    "professions",
                    models.ManyToManyField(
                        blank=True, related_name="singers", to="music.perfession"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("release", models.DateField()),
                ("time", models.IntegerField()),
                ("lyric", models.TextField()),
                ("description", models.TextField()),
                ("file_mp3", models.CharField(max_length=250)),
                ("categories", models.ManyToManyField(blank=True, to="music.category")),
                ("countries", models.ManyToManyField(blank=True, to="music.country")),
                ("singers", models.ManyToManyField(blank=True, to="music.singer")),
            ],
        ),
    ]
